### ISSUE TITLE
Runs in Isolated world on Chrome 109/Win7

### ISSUE THREAD

**Issue by lance8765** [RePod/psdle#117]
**Browser:** (Chrome 109)

**Method:** (Extension)

**Online store version and language:** (Desktop) (it-it)

**PSDLE version:** 4.2.0

**Is Catalog enabled:** (Yes)

---

**Problem:** PSDLE simply no longer works for me. I tried going to the Library and choosing between PS4/PS5 or Transaction History, it loads a page, but nothing PSDLE-related appears. Also, i have secondary PSN account(s) and i use PSDLE on them on a regular basis, by logging from Incognito mode (so i don't have to log out from my main account every time), now after choosing between PS4/PS5 or Transaction History, it opens a new page/tab (as intended) BUT in non-Incognito mode. Going to Account Settings and then Transaction History doesn't improve the situation. Payment Management is toast, too. I'm starting to regret having opened issue #115 at this point (sorry!)

**How to replicate:** Just try it maybe with a dummy account on Italian Store?

**Other notes:** Userscript version is still v4.1.4, but only for PS4/PS5 games.

**Comment by RePod** [comment]
re: https://github.com/RePod/psdle/issues/115#issuecomment-2218099049
The 109 version requirement is for Firefox and similar, which I am noticing an issue with but not on Chrome 126.

If possible try updating Chrome although MV3 support was recommend as far back as 88. Barring that, Ctrl+Shift+J to get logs from the console.

**Comment by lance8765** [comment]
Which means... PSDLE now requires Windows 10/11 browsers? Oh. Due to not having upgraded my PC in more than a decade i'm forced to stay on W7. Is there a way to revert back to extension v4.1.4?

**Comment by RePod** [comment]
> PSDLE now requires Windows 10/11 browsers?

The extensions maybe due to upgrading to Manifest V3 and especially in Firefox's case for dragging out supporting `MAIN` which is key to how the extensions inject PSDLE. The manual/userscript versions should be fine whenever I send them out.

> Is there a way to revert back to extension v4.1.4?

It's more involved and not permanent, but:
 - [Download the older repo](https://github.com/RePod/psdle/archive/10be852647e63483477e15b2acaeb1fccbea1396.zip)
 - Move:
     - `_src/base/valkyrie/psdle.valkyrie.includes.js` to `_src/chrome/psdle/js/psdle.valkyrie.js`
     - `_src/base/gotham/psdle.gotham.includes.js` to `_src/chrome/psdle/js/psdle.gotham.js`
 - Navigate to `chrome://extensions`
 - Enable *Developer Mode* in the top right
 - *Load Unpacked* in the top left
 - Select the `_src/chrome/psdle` folder (you'll see the `_locales`/`icons`/`js` folders)
I don't endorse or confirm the safety of third-party extensions mirrors but that may also be an option.

I *could* roll back the extension on the stores but this delays the inevitable.

```
chrome.js:1 PSDLE Chrome | radio static I'm in Window {window: Window, self: Window, document: document, name: '', location: Location, …} #document
psdle.gotham.js:9 PSDLE 4.2.0 2024-07-08
psdle.gotham.js:15 Uncaught TypeError: Cannot read properties of undefined (reading 'appProps')
```
This fortunately is not an extension error but rather something with Gotham which is weird since I didn't touch it aside from how it's injected now. I'll try to get my hands on a version of Chrome 109 for further testing. Logs from a Transaction History/Payment Management run would also be good.

**Comment by lance8765** [comment]
Ok, take your time. And thanks for the instructions for the previous version.

**Comment by RePod** [comment]
Please try the above instructions but with [this zip.](https://github.com/RePod/psdle/archive/refs/heads/mv3v2.zip)
It's still MV3, as that was not the main issue, but it's back to injecting like before despite being less elegant.

**Comment by lance8765** [comment]
Ok, that one works on Chrome 109, the only difference is that Payment Management is extended to (almost) full screen instead of being on the right side, but whatever.

**Comment by RePod** [comment]
Payment Management being expanded is intended. Previously the width of the drawer was set to 100% but now it's 95% so it can also be closed normally.

The PS_PLUS_REQUIRED has now appeared for me on games I know I purchased while also failing to load their icons. It's beyond me. The distinction might need to be changed because I'm not getting PS+ to check.

The original goal was to migrate to MV3 but I would like to eventually, within the next 10 years, return to injecting the script as intended.

**Comment by lance8765** [comment]
> Payment Management being expanded is intended. Previously the width of the drawer was set to 100% but now it's 95% so it can also be closed normally.
> 
> The PS_PLUS_REQUIRED has now appeared for me on games I know I purchased while also failing to load their icons. It's beyond me. The distinction might need to be changed because I'm not getting PS+ to check.
> 
> The original goal was to migrate to MV3 but I would like to eventually, within the next 10 years, return to injecting the script as intended.

You mean PS_PLUS_REQUIRED **_and_** being at the top of the list with broken icons? Because if you only mean PS_PLUS_REQUIRED but still have the items in correct position, that other issue is ancient. It's like they are having fun automagically turning free non-Plus content into Plus content, i lost several content on my secondary accounts because of that. And there's no way to make them understand the issue. Sheesh.

**Comment by RePod** [comment]
All three at once though the the label chosen for PSDLE might be inaccurate. I cannot force the information to exist so that's the extent of my concern.

**Comment by lance8765** [comment]
> All three at once though the the label chosen for PSDLE might be inaccurate. I cannot force the information to exist so that's the extent of my concern.

I'll never understand why it happens, it cannot be avoided etc... but it eventually fixes by itself after some time, days, weeks, even months. It's weird. Something hates when you redownload legacy content.
