### ISSUE TITLE
Catalog - TypeError undefined

### ISSUE THREAD

**Issue by EvilCanasta** [RePod/psdle#14]
I'm sorry to open a new issue but you should've let me close it when it was really solved... i didn't manage to finish creating the list with your latest link, with Catalog enabled. Anyway, the counter gets stuck at 642 items, i see this error from the console:

TypeError: data.metadata.secondary_classification is undefined

**Comment by RePod** [comment]
Not a problem, and this is a separate issue entirely with the Catalog.

However, due to you including the error this is an easy fix.

[Try this.](https://gist.githubusercontent.com/RePod/dd8aa124e12c82348c08/raw/e2cdcf6bddc3dae02579a976682868a0f9d3054f/gistfile1.txt)

**Comment by EvilCanasta** [comment]
Still gets stuck at 642, this time is "data.metadata.primary_classification is undefined"

**Comment by RePod** [comment]
[One more...](https://gist.githubusercontent.com/RePod/dd8aa124e12c82348c08/raw/231c1ffc40471ea03a0d6d46daf02c3464ec706b/gistfile1.txt)

**Comment by EvilCanasta** [comment]
This one works with and without Catalog, but the bug with certain PS1/PS2 Classics listed under PS3 (Warhawk and Twisted Metal Black, respectively) i mentioned in the other discussion has returned. But hey, at least it works!

**Comment by RePod** [comment]
I'm working on implementing more debug tools to assist in figuring out what is causing this.

When on the it-it store, and PSDLE has been started, try running the following in the console:
>repod.psdle.debug.checkParse("[EP9000-NPEC00001_00-GTWISTEDME000001](# "Twisted Metal Black's product ID")")

It should spit out the information it gets back from the Catalog, and when I try it the "platform" attribute is returned as "PS2". Just want to verify you're getting the same results.

Also, when I tried generating a fake list using the catalog and TMB it was properly classified as a PS2 game. Please try the latest version to confirm if I didn't randomly fix it since I have since done a lot of changes around the code where it figures this stuff out.

**Comment by EvilCanasta** [comment]
Do you mean "started" as using the latest version released hours ago?

**Comment by RePod** [comment]
Thanks for the confirmation, I'll be looking into it.

>Also the new version seems to be faster than the ones you told me to use in the previous posts.

I had accidentally removed a few calls, which I recently [added back](https://github.com/RePod/psdle/blob/1235f7ee9af008f731e6930a0b171d17b427a426/psdle.js#L235).

**Comment by EvilCanasta** [comment]
Uhm i think something got messed up with the latest revision of PSDLE... first, Catalog is disabled by default (not a big deal), second, there's no difference between choosing "Export View" or downloading the .CSV file, they're formatted the same in both cases...

**Comment by RePod** [comment]
Catalog is disabled by default now. It's been on my list for a while and since I ironed out a majority of the Catalog problems I thought this was a good time to do it.

Export View generates the textbox to copy paste, CSV generates an actual download.

**Comment by EvilCanasta** [comment]
I understand, but it worked better before... you could get 4 different columns by copying everything on a spreadsheet, now you get a single column with all info about Name,Platform,Size,Date, (and PS+,PS TV, too if you happen to enable them), i mean it was like seeing the PSDLE list, just without the icons.

**Comment by RePod** [comment]
>Now you get a single column with all info about Name,Platform,Size,Date, (and PS+,PS TV, too if you happen to enable them)

Fixed, was a small absence in the code. "Export View" now properly uses the given separator.

>Do you know if the following problem with the Download List has anything to do with your plugin, or it's just a problem with their site?

I have no idea. All I can say PSDLE is generating the Download List in the same way as the store so there would be little difference between the two.

**Comment by EvilCanasta** [comment]
Nice :D i love the new PS+ column.

I just asked about that bug with the Download List because, like it's written in that link, the problem began earlier this year, and PSDLE got some major changes (just guessing) this year, too. It's a really weird problem anyway... i just thought that maybe the list "freezes" after you use the script and then you have to clean the browser or use a different one to "fix" it.

ps: do you think it'll be possible to make the exported .CSV file the same as the one you obtain by manually copying the text? I mean, with the separators and in multiple columns? Or maybe just fix the special characters? It's just because some special characters aren't exported properly, i.e. (PAYDAY™ The Heist - Trial) is read as (PAYDAYâ„¢ The Heist â€“ Trial). Again, this only happen with the .CSV file, the other method has everything working properly.

**Comment by RePod** [comment]
>do you think it'll be possible to make the exported .CSV file the same as the one you obtain by manually copying the text? I mean, with the separators and in multiple columns?

Definitely possible, it's as simple as prompting for a user-defined separator. However, aside from delimited which already does this, it would no longer be "*Comma*-separated values" (CSV) which speedsheet programs might expect.

>It's just because some special characters aren't exported properly

Make sure when you're opening or importing it into your speadsheet software it's being detected as UTF-8. I had a similar issue using LibreOffice Calc, forcing it to UTF-8 fixed everything. I cannot do anything more about this.

![screenshot_4](https://cloud.githubusercontent.com/assets/7897871/6413099/c1c1b316-be59-11e4-8884-01da6a0ce5aa.png)


>did you remove the "total size" at the bottom of the exported list?

The totals are not included with exporting for now since I need to rewrite how the totals are generated. I'm thinking of including totals for other columns like the number of PS+ or PS TV rows.

>Also, shouldn't PS TV be completely greyed out for the EU site?

Yes, however at the moment since the options are generated dynamically without taking into account what's actually available, PS TV is included in the export options.

**Comment by EvilCanasta** [comment]
I see. Well after importing the file (i use Excel 2010) it looks like exactly the one i copy/paste manually. Same format, same number of columns, and the special characters seem to be correct. I wish there's a way to automatically import files like that, since i rarely use that format and i'll probably forget it very soon (actually, i think that's the first time ever i had to IMPORT a .CSV file haha). Thanks for the tip.

Got any news on that problem with the mislabeled PS1/PS2 games?

**Comment by RePod** [comment]
None in particular, recently updated the website with Bootstrap which consumed most of my time.

However I would assume it's an easy fix once I focus on it specifically. I have a large to-do list I'm working through while also keeping track of feedback and other reports.

**Comment by EvilCanasta** [comment]
I see. Oh and sorry i had to edit my previous post.

**Comment by RePod** [comment]
>But now it just happens without Catalog enabled, not in both cases.

System detection is primarily [determined by the Entitlements information](https://github.com/RePod/psdle/blob/master/psdle.js#L203-L206) then the Catalog overwrites it if enabled. Outside of that I cannot control it.

**Comment by EvilCanasta2** [comment]
Hi, it's me again, but i've lost my previous account. Can you please close this issue? Thanks.
