### ISSUE TITLE
Various questions/suggestions:

### ISSUE THREAD

**Issue by EvilCanasta2** [RePod/psdle#16]
Hi again, your addon seems to be working fine for now (except for those mislabeled PS1/PS2 games, but whatever), however i have a couple of things to ask:

1) Do you think it'll ever be possible to put multiple items in the download queue, at once? Maybe through a selector or something. While it's better to use your plugin, since you can see ALL your download list, and not multiple pages, it still takes a little more time than using the normal list.

ps: just in case you're wondering, i think the actual limit on the queue is around a hundred items, but apparently, it starts going apes*** after just 30-ish items. Like download failures and crap like that.

2) Still about the download queue, do you think it'll ever be possible to display "queued" items in a different color, in the main list? I'm not talking about the "Download to PS3" button that becomes green, i'm talking about the list itself. Just like PS+ items are displayed in yellow. And maybe put an easier way to DELETE them from the queue? I think you have to click TWICE on the items as of now, but the script doesn't tell you to do so as of now.

3) Will it ever be possible to disable the "Icon" column on the main list with a filter? Do you think that disabling them would make scrolling down the list a little faster? Also will it ever be possible to EXPORT them someday? I know it'll probably never be possible with CSVs, but still...

Thank you in advance, as usual.

**Comment by RePod** [comment]
>Do you think it'll ever be possible to put multiple items in the download queue, at once?

Definitely possible, and has been done before. When I first implemented the Download Queue it sent a selected list of items to the queue, however only to PS3 for testing. I need to find a way to cleanly prompt for how users want to handle the selected list: per-item (pick where each goes) or automatically (based on what should be the playable system). The solution also has to be accessible on mobile.

>... do you think it'll ever be possible to display "queued" items in a different color, in the main list?

Probably possible, the biggest hurdle is displaying it. Before, PS+ status made the entire row yellow but has since been trimmed down to a border around the icon. I would like to avoid having something take up the entire row again. Another small hurdle is matching the content from the Queue to its List counterpart. This is already kinda done when viewing the Queue but it's very inefficient.

>And maybe put an easier way to DELETE them from the queue? I think you have to click TWICE on the items as of now

That's a binding issue that should only require clicking twice the first time. I could work that out and throw in message above the list and a prompt (requiring translation updates).

>Will it ever be possible to disable the "Icon" column on the main list with a filter?
>Do you think that disabling them would make scrolling down the list a little faster?

Yes, it would be possible to disable the Icon column. No, I don't think it would make scrolling the list a little faster. The icons on the list take up 42x42px (48x48 after padding) , obviously taller than a standard row, but provide a lot of vertical padding on the list to make it easily readable. Also, the border of the image is currently the only indication of PS+ status aside from opening the window when clicked. I think this could easily be remedied by throwing a PS+ icon in the Icon column instead of removing it (see second image below).

Here's an image of if they were 31x31px (37x37 after padding):

![screenshot_9](https://cloud.githubusercontent.com/assets/7897871/6652784/7615b33c-ca51-11e4-8e60-5b9382dac614.png)

Things start to get a little cramped. The only other source of padding is from the "Name" column, but with that removed:

![screenshot_10](https://cloud.githubusercontent.com/assets/7897871/6652805/1b3ed578-ca52-11e4-9ff2-483bfdc0b551.png)

Definitely understand the advantages though, but as most things I need a way to present the option easily between multiple languages and mobile devices.

>Also will it ever be possible to EXPORT them someday?

Definitely **NOT** possible, at least easily for casual usage. Unless people want the API URLs they can't do much else with them except manually download every single one. However, the URLs are available if *repod.psdle.gamelist* is exported as JSON.

**Comment by EvilCanasta2** [comment]
Thanks for all the answers! :)
