### ISSUE TITLE
TV content (as TV series) being ignored by PSDLE?

### ISSUE THREAD

**Issue by Mattrex87** [RePod/psdle#32]
Hi, i usually get only gaming-related content on my PSN account, i also have like THREE movie trailes and they do appear in the results of the PSDLE list (duplicated, because of SD/HD formats)

Now i've just discovered that the series "Powers" has been finally released, for free (at least for PS+ users) in EU regions, after months of waiting. So i decided to grab all episodies, because i said, who cares, it's free. The problem is, these things are omitted from the list generated by PSDLE. Could you please add support to TV series in PSDLE? Thank you.

ps: i perfectly understand that these are not games or DLC, but like i said, movie trailers (and i guess movies, too, since they should appear under the same "category" in the Download List when you browse them from PC) are NOT omitted from PSDLE. It's been like that for ages.

ps2: just checked from my PS3 and all episodes of that series appear in my Download List.

**Comment by RePod** [comment]
Thank GitHub for not emailing me.

>TV content (as TV series) being ignored by PSDLE?
As for this question itself, yes. Specifically [around this line](https://github.com/RePod/psdle/blob/31d8ac87ae6e48b381a2a4c4f121a1e271eafb92/psdle.js#L313).

Simply disabling that should include all video content as well.

However, as you pointed out PSDLE seems intended for games but that is not the real answer.
PSDLE is more oriented towards the *systems* (PS3/4/Vita) to tie everything together.

Video content may work "out of the box" but since PSDLE only cares about the systems you'd be limited to those and wouldn't get the expansive array of options the store provides natively such as resolution, sending it to something else (Phone, Media Go, TVs), etc.

However, barring these limitations I am now considering adding a new option to the start up screen (where you pick Catalog/etc) to not run these content checks.

To imagine a world without excluding non-game content use [this modified version of PSDLE](https://gist.github.com/RePod/ae060ede3a88a4c14433c6b34c5b1f71) and do the following:
 - Open the browser console:
  - **Firefox:** `Ctrl + Shift + K`, **Chrome:** `Ctrl + Shift + J`
 - Paste the contents of the link and submit

If that is to your liking, I'll definitely consider working out a way to toggle it.

As for extraneous video content, like trailers, it's most likely the checks I added are basic and don't cover every edge case (because I wasn't looking for them).

**Comment by Mattrex87** [comment]
I don't understand how to use that modified version of PSDLE :/

**Comment by RePod** [comment]
Open the browser console with the appropriate keyboard combination.
If not using Firefox/Chrome, state your browser and I'll get you the correct one.

Afterwards a new window/panel will appear with a place to input text, paste the modified version into it and press enter.

**Comment by Mattrex87** [comment]
Yes, it works, although i'm getting two omitted results (with and without Catalog)

Few things i've noticed:

- Without your modified version of PSDLE, i normally get all my items, without missing stuff.
- The "Powers" episodes are 17 according to my Download List. However, it only shows 15 of them with your modified PSDLE, it omits two "Episode 0", one for each season. Unlike the other episodes, those two cannot be watched from the Download List (or downloaded at all?)
- On my PS3's Download List, and under Account Managament on the SEN site, i get TWO entries for each episode, one for SD movies, and the other for HD. I only get the SD stuff in the script.
- One of the episodes has the "purchase" date set to tomorrow (?), this one doesn't appear under Account Management's list. There are also two entries named "Powers: Season 1:1" and "Season 2:2" (i wonder if they're just the two "Episode 0" i previously mentioned?)

**Comment by Mattrex87** [comment]
So... nothing new? It's been a while and they finally released the final episode of Season 2.

**Comment by RePod** [comment]
Nothing in the code, no.

The furthest I got with it was an idea for PSDLE to "minimize" itself and go to the item's store page (to access the store's downloading options) but that almost defeats the purpose of using it.

As stated above though: media/non-game content, more so those which are available beyond the PlayStation consoles and handhelds, have a lot of options that PSDLE currently doesn't replicate and would be an immense undertaking to do so:
 - Detecting more devices on the account
 - Properly sending queue information (I had to figure out PS3/4/Vita myself)
    - Although I would assume it'd be the same for PS3/4/Vita, the rest of potential devices may not be
 - Reading the video queue information (which I personally would be limited to console queues)

I apologize, but at this time I cannot see support for media/non-game content expanding.
At most I can add an option to not exclude the content, but then you'll be limited to the available resolution (SD as you said) and *only consoles* (not Media Go, phones/tablets, TVs, etc).

**Comment by Mattrex87** [comment]
Oh, now i understand why the movie trailers i have are in the PSDLE list... it's because they're only for PS3 and PSP (i got them ages ago)

Limiting the content to consoles only would be better than nothing. PSDLE is only about Sony GAMING systems, after all... :)

ps: talking about "minimize", it would be great to get an option to just minimize PSDLE so it won't be necessary to reload the Store site every time you want to get back to it. Too bad it is really sluggish...
