### ISSUE TITLE
Sorting by genre results in list disappearing

### ISSUE THREAD

**Issue by gerbil-snot** [RePod/psdle#61]
Seems to work well, but what I really wanted was to sort my games by genre; unfortunately, it seems the feature doesn't work. After selecting the option, it just causes my entire list to disappear.

**Comment by RePod** [comment]
Please try [this version](https://raw.githubusercontent.com/RePod/psdle/master/psdle.js).
Copy-paste into browser's console (Chrome: Ctrl+Shift+J, Firefox: Ctrl+Shift+K) before I push it to all versions.

----

Currently the search box is very limited, so you may notice the autocomplete searching is a bit convoluted.
I'm considering a tag-based search in the future.

**Comment by gerbil-snot** [comment]
That seemed to have worked, the list doesn't disappear anymore.

It'd be useful if it would show what genre the game is listed under though.

**Comment by RePod** [comment]
I wouldn't even be sure where to begin on sorting genres, I've never seen such a sort in practical use. The ordering would completely shoot down sorting, filtering seems to be the only option.

Right now the best alternative is filling in the search box based on the autocomplete list.
Regex is also possible for more advanced searches i.e. `/(action|adventure)/i` for action *or* adventure instead of both.

**Comment by gerbil-snot** [comment]
It's still a very useful tool, just thought I'd throw the idea out there.

Thanks for the quick fix!

**Comment by RePod** [comment]
Just for future reference as to where the difficulty in sorting by genre comes from:
![2018-12-03_13-01-57](https://user-images.githubusercontent.com/7897871/49392182-afb68a00-f6fb-11e8-917e-eb7ad29c91f9.png)
Ignore this order, this is the order they're added to the autocomplete in. Which would a user prefer to see higher in the list, `Casual,Unique` or `Unique,Casual`. They're the same but the order of them is completely irrelevant but hard to sort on. The `MUSIC/RHYTHM` genre is also harder because that's how it is instead of a possible `RHYTHM/MUSIC`.

If and when the search gets tags instead like `tag:Unique` or `system:PS3` (each with individual autocompletes) this will be less of an issue.

But for now genres are fixed at least so net gain.

**Comment by gerbil-snot** [comment]
That makes sense, for someone who isn't familiar with this kind of stuff. Thanks for the help.
