### ISSUE TITLE
Generated list omits some content from my account

### ISSUE THREAD

**Issue by Goliz** [RePod/psdle#7]
I have thousands of entries on my PSN download list, including games, DLC, themes, demos, avatars, and so on. However, the list omits around 30 of those entries (out of a total of 2448... that's my situation, others will have different numbers, of course) if i generate it with the option "Catalog" enabled. If i disable it, the list is generated quickly, and it shows exactly 2448 entries. The omitted content is mostly stuff obtained years ago. I thought keeping "Catalog" enabled gave more accurate results?

**Comment by RePod** [comment]
If I had to guess it's due to the systems being detected on the hidden content not being those actually allowed (PS1/2/3/4/P/V) thus while PSDLE does acknowledge them it doesn't consider them valid to the search options selected.

I could either include an "Other" system category (which ignores these checks) or ensure those ones get set to a system they can actually be used on. Since it sounds like you may know what's already being excluded would it be too much to ask if you name those content items (and on what store language)?

**Comment by Goliz** [comment]
I'm afraid i don't know what i'm supposed to do with that URL. Are you sure the steps are correct? I've never ever used the console before.

**Comment by RePod** [comment]
The URL contains a modified version of the PSDLE javascript. You should be able to execute it from the browser console.

In Firefox it would look like so: (your color/theme might be different)
![console](https://cloud.githubusercontent.com/assets/7897871/5986474/d50c0172-a8c6-11e4-89fa-07ea8dc5a4fa.jpg)

**Comment by Goliz** [comment]
Ok, i've found around 19 "Bad sys?" entries, but a lot more "Bad type?". What should i do now?

Anyway, the "Bad" entries are all for old PSP content, purchased ages ago, i.e. Quiz packs for Buzz! games, addons for Toy Story 3, Dissidia Duodecim, and so on. My account is Italian, by the way.

**Comment by RePod** [comment]
Posting a few of of the results would help, then I'll check them on the Italian language web store.

**Comment by Goliz** [comment]
I just copy-pasted all of them, should be easy to check though: http://pastebin.com/FnUJXuyv

**Comment by RePod** [comment]
Please do the same steps as above but with [this url](//gist.githubusercontent.com/RePod/0aeefb86a7657f1b1bf4/raw/ce91612e8a44f1d78eefc13cb38416c64fb2c69f/PSDLE).

I think I found the problem. Also, most of the "bad type?" from before were due to the logging line being in the wrong place, it is now where it should be for testing.

**Comment by Goliz** [comment]
Well, now i'm getting a lot more omitted results than before (711, basically most of my pre-2012 content), but the "bad" entries are still 200 as before, although all of them are "Bad sys?" this time: http://pastebin.com/P4wfdW3b

**Comment by RePod** [comment]
Please try [this url](//gist.githubusercontent.com/RePod/0aeefb86a7657f1b1bf4/raw/9751cfbb082b703d273778bb755605910d4af399/PSDLE).

Thanks!

**Comment by Goliz** [comment]
No problem. Now it shows 2448 out of 2448 entries, like it should be. No need to post anything.

**Comment by RePod** [comment]
Great! Time to rewrite the system detection

As for exporting, if there is demand for it I prioritize it. The entire export option was done on a whim before anybody actually requested it and people just used it. It needs to be rewritten so people can pick exactly what they want.

However, running _JSON.stringify(repod.psdle.gamelist_cur)_ in the console will return a string of all information PSDLE has on the current view in JSON format. Paired with prompt() you should be able to easily copy it.

**Comment by Goliz** [comment]
I see, thank you.
